### ISSUE TITLE
release_id

### ISSUE THREAD

**Issue by randallsquared** [inadarei/rfc-healthcheck#11]
Is there a reason `release_id` is snake_case, and everything else camelCase?  If not, let's change it.

**Comment by inadarei** [comment]
Good catch, thank you! It should indeed be consistent.

One last sanity check before we make final change - should everything be snake-case or camelCase? Not sure if there's a more commonly adopted pattern in JSON?

I generally don't like cased anything because not I personally feel it is more error-prone that snake-cased (and harder to read) but that's just me. 

Are we set on camel-case?

**Comment by randallsquared** [comment]
I'm not set on anything, and don't think it matters overmuch; the important thing is that its decided and final.

**Comment by inadarei** [comment]
LOL! That comment seemed very set on being non-committal :)

**Comment by randallsquared** [comment]
We as a community have argued about this for decades.  Nobody has convincingly won.   Therefore it’s a bad idea to spend rfchealthcheck time on the argument.   Pick one to standardize on, and we can ignore the whole thing for this RFC indefinitely.  :)

**Comment by inadarei** [comment]
OK, CamelCases win.

**Comment by inadarei** [comment]
I believe this is now fixed with the latest merge
