### ISSUE TITLE
initializing status?

### ISSUE THREAD

**Issue by justincormack** [inadarei/rfc-healthcheck#18]
I think I really want a status for initialising, ie "not yet healthy but so far can't see any reason why I won't be at some point". Or should I use a WARN state for that? These states can be quite long (eg database recovery is the classic example) and are not healthy in that requests can be served but they are not failed.

**Comment by inadarei** [comment]
That's very interesting. The question here becomes – can the service process requests or not? If the answer is "no" then it is "fail" by definition. However if you want to hint to the client that "but, I will be able to do it soon" - why not put that additional information in the "notes" section?

**Comment by inadarei** [comment]
WARN is for cases where service is able to process requests but is reaching dangerous zone capacity-wise or stability-wise. If that is the case in the initialization stage, then warn can be used, otherwise it should be fail. It's a judgement call from service provider to decide which case is more appropriate.

In cases where initialization (and shutdown, by the way) cases are so pronounced that they need more than just a note - we have to refer to already-established approach in the industry, instead of reinvented something. This case is, indeed highlighted in Kubernetes but instead of a separate set of statuses they have gone with  multiple endpoints: readiness probe and liveness probe are two different endpoints, whereas each one of them have simple status responses: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

I believe we should follow that guidance to have standard reflect de-facto common behavior. You can see how this is implemented for Node.js using the existing RFC and Kubernetes-compliant approach here: https://github.com/inadarei/maikai#kubernetes-liveness-and-readiness-probes

**Comment by tgeliot** [comment]
> WARN is for cases where service is able to process requests but is reaching dangerous zone capacity-wise or stability-wise.
Is this part of some standard or something?  Can you please direct us to it?  Or is it just your intent for this standard?  Somewhere in the Kubernetes documentation I saw a reference to having three possible return statuses:  pass, fail, and unknown.  No "warn".  Sorry, I can't find that page now.

As for liveness / readiness being two separate concepts and/or endpoints, that seems like a good idea.
It's good enough that I wonder if there's some appropriate way to mention in connection with this RFC, even though it wouldn't be prescriptive.

Is the idea that an app would present two endpoints, one for liveness and the other for readiness, and each would obey this standard for a health check API?

Nice piece of work in maikai, thank you for your contribution to the community.

**Comment by inadarei** [comment]
> Is the idea that an app would present two endpoints, one for liveness and the other for readiness, and each would obey this standard for a health check API?

Yeap, that's how things work in the Kubernetes world.

Many t hanks for your kind words re: Maikai. Much appreciated.
