### ISSUE TITLE
Clarify supported HTTP methods

### ISSUE THREAD

**Issue by 0xced** [inadarei/rfc-healthcheck#37]
What HTTP methods should be supported? I think this should be clarified.

My opinion is that only `GET` and `HEAD` should be supported and other methods should trigger a *405 Method Not Allowed* response with a Allow header: `Allow: GET, HEAD`

This issue is somewhat related to #8.

**Comment by inadarei** [comment]
Current spec cannot support HTTP HEAD because it documents response body in JSON and HTTP HEAD doesn't return any body so I am not sure how that would work.

**Comment by 0xced** [comment]
As I see it, the spec could document that `GET` MUST be supported and that `HEAD` SHOULD be supported as it can still be useful to get only pass/warn/fail information without more details through the HTTP status code.

**Comment by MikeRalphson** [comment]
Should `OPTIONS` be explicitly supported for CORS?

**Comment by inadarei** [comment]
The comments about HEAD and OPTION are all good points but still feel irrelevant to this specification since this specification is about standardizing content payload for the response type (GET) that actually can respond with the payload. it is not be-all and end-all of health checking, least of all - duplication of general good API practices (e.g. properly supporting CORS).

just my 2c

**Comment by christianhujer** [comment]
Specifying the methods to me sounds redundant with what HTTP already says. It's pretty obvious: `GET`, `HEAD`, `OPTIONS`. Anything beyond that would be beyond the specification.
For example, there could be a health aggregation service which supports `POST` and `PUT` for `/health`. The specification should not make a mention of this at all, to neither mislead users nor to disallow reasonable extensions.
